apiVersion: apps/v1
kind: Deployment
metadata:
 name: issue-tracker
 labels:
   app: issue-tracker
spec:
 replicas: 3
 selector:
   matchLabels:
     app: issue-tracker
 template:
   metadata:
     labels:
       app: issue-tracker
   spec:
     containers:
     - name: issue-tracker
       image: jp.icr.io/issue_tracker/issue_tracker:2.0
       ports:
       - containerPort: 5000


